apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: guestbook-spoke2
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Keerthan2006/multicluster-argocd.git
    targetRevision: HEAD
    path: manifests/guestbook

  destination:
    server: https://172.22.0.8:6443
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
